### ISSUE TITLE
AttributeError: 'PyTorchTensor' object has no attribute 'tensor'

### ISSUE THREAD

**Issue by pratyushmaini** [jonasrauber/foolbox-native#9]
File ".../foolbox/ext/native/attacks/basic_iterative_method.py", line 98, in __call__
    gradients = ep.astensor(self.model.gradient(x.tensor, y.tensor))
AttributeError: 'PyTorchTensor' object has no attribute 'tensor'

I get the following error on running the example code. I am using the right version of Pytorch as required. Probably the PyTorch attack is being directed to the TensorFlow version somewhere.

**Comment by jonasrauber** [comment]
That's because I've recently updated EagerPy and the latest release of Foolbox Native has not yet been adapted to these changes. Just downgrade EagerPy to I think 0.15.0.

**Comment by pratyushmaini** [comment]
Thank You!
